// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJoTWgu3dvUx2pQ025DQK96112NaVDfic',
    appId: '1:250825983830:web:1851b417e880bad23578f7',
    messagingSenderId: '250825983830',
    projectId: 'chat-8da41',
    authDomain: 'chat-8da41.firebaseapp.com',
    storageBucket: 'chat-8da41.appspot.com',
    measurementId: 'G-FE960D1C0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1gyp3up3ar0Uy5IZAKZzuStdXI2Ymzw',
    appId: '1:250825983830:android:13571f56b8e1cacb3578f7',
    messagingSenderId: '250825983830',
    projectId: 'chat-8da41',
    storageBucket: 'chat-8da41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXrD6DqKb9xHqxngSlvhjhv3gBZTcctVc',
    appId: '1:250825983830:ios:66d3db577372fb6a3578f7',
    messagingSenderId: '250825983830',
    projectId: 'chat-8da41',
    storageBucket: 'chat-8da41.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXrD6DqKb9xHqxngSlvhjhv3gBZTcctVc',
    appId: '1:250825983830:ios:66d3db577372fb6a3578f7',
    messagingSenderId: '250825983830',
    projectId: 'chat-8da41',
    storageBucket: 'chat-8da41.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJoTWgu3dvUx2pQ025DQK96112NaVDfic',
    appId: '1:250825983830:web:61e9ccad2664a8563578f7',
    messagingSenderId: '250825983830',
    projectId: 'chat-8da41',
    authDomain: 'chat-8da41.firebaseapp.com',
    storageBucket: 'chat-8da41.appspot.com',
    measurementId: 'G-ZZSMR4C3V1',
  );
}
